name: Shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run shellcheck of .sh files
        run: |
          shopt -s globstar
          shellcheck -x -- **/*.sh
